from __future__ import annotations

from typing import Any

from hermes_decompiler.analysis.terminators import Terminator
from hermes_decompiler.ir.expressions import Expression
from hermes_decompiler.ir.statements import Statement
from hermes_decompiler.frontend.opcode.OpcodeEntry import OpcodeEntry


class OpcodeResult:
    """
    The single record produced by handling one bytecode opcode.

    Replaces the earlier OpcodeResult + JSVariable pair. `handler` and
    `address` were pure duplicates of `entry.opcode`/`entry.address` and
    are now derived properties; `value`/`statement`/`used`/destination
    register are owned directly here instead of through a separate
    wrapper object, so a handler builds exactly one `OpcodeResult`,
    registers it via `analysis.add_result(result)`, and returns that
    same instance - there is no longer a second, separately constructed
    `OpcodeResult` for the same opcode.
    """

    __slots__ = (
        "entry",
        "value",
        "terminator",
        "statement",
        "dest_reg",
        "definition_used",
    )

    def __init__(
            self,
            entry: OpcodeEntry,
            value: Expression | None = None,
            statement: Statement | None = None,
            terminator: Terminator | None = None,
            dest_reg: int | None = None,
    ):
        """
        Args:
            entry: The opcode this result was produced from. Also, the
                source of `handler`/`address` (see properties below).
            value: The IR expression this opcode's destination register
                now holds, if any (`None` for pure control flow with no
                operand, e.g., an unconditional jump).
            dest_reg: The destination register index, if this opcode
                writes one. Used to derive `name` (`"r{dest_reg}"`).

        Raises:
            TypeError: if `entry` is not an `OpcodeEntry`.
            ValueError: if `dest_reg` is negative, or if `value` is
                supplied without a `dest_reg` to hold it.
        """
        if not isinstance(entry, OpcodeEntry):
            raise TypeError(
                f"entry must be an OpcodeEntry, got {type(entry).__name__}"
            )
        # if dest_reg is not None and dest_reg < 0:
        #     raise ValueError(f"dest_reg must be non-negative, got {dest_reg}")
        # if value is not None and dest_reg is None:
        #     raise ValueError("value provided without a dest_reg to hold it")

        self.entry = entry
        self.value = value
        self.terminator = terminator
        self.statement = statement
        self.dest_reg = dest_reg

        # Shows: the expression generated by this instruction was
        # inlined into another expression and no longer needs to be
        # emitted on its own.
        self.definition_used = False

    # ------------------------------------------------------------------
    # Derived from `entry` - no longer separately stored/duplicated.
    # ------------------------------------------------------------------

    @property
    def address(self) -> int:
        return self.entry.address

    @property
    def handler(self):
        return self.entry.opcode

    @property
    def name(self) -> str:
        if self.dest_reg is None:
            return ""
        return f"r{self.dest_reg}"

    def __repr__(self) -> str:
        return (
            f"OpcodeResult("
            f"address={self.address}, "
            f"handler={self.handler!r}, "
            f"name={self.name!r}, "
            f"value={self.value!r}, "
            f"used={self.definition_used})"
        )

    __str__ = __repr__

    def to_dict(self) -> dict[str, Any]:
        """
        JSON-friendly summary. `value`/`statement`/`terminator` are
        stringified rather than embedded as-is, since they may not be
        serializable on their own.
        """
        return {
            "handler": self.handler,
            "address": self.address,
            "name": self.name,
            "value": repr(self.value) if self.value is not None else None,
            "statement": repr(self.statement) if self.statement is not None else None,
            # "terminator": repr(self.terminator) if self.terminator is not None else None,
            "used": self.definition_used,
        }
