from __future__ import annotations

import itertools
from typing import Any

from hermes_decompiler.analysis.terminators import Terminator
from hermes_decompiler.ir.expressions import Expression
from hermes_decompiler.ir.statements import Statement
from hermes_decompiler.frontend.opcode import OpcodeEntry

_next_def_id = itertools.count()


class OpcodeResult:
    """
    The single record produced by handling one bytecode opcode.

    Replaces the earlier OpcodeResult + JSVariable pair. `handler` and
    `address` were pure duplicates of `entry.opcode`/`entry.address` and
    are now derived properties; `value`/`statement`/`used`/destination
    register are owned directly here instead of through a separate
    wrapper object, so a handler builds exactly one `OpcodeResult`,
    registers it via `analysis.add_result(result)`, and returns that
    same instance - there is no longer a second, separately-constructed
    `OpcodeResult` for the same opcode.
    """

    def __init__(
            self,
            entry: OpcodeEntry,
            value: Expression | None = None,
            statement: Statement | None = None,
            terminator: Terminator | None = None,
            dest_reg: int | None = None,
    ):
        """
        Args:
            entry: The opcode this result was produced from. Also the
                source of `handler`/`address` (see properties below).
            value: The IR expression this opcode's destination register
                now holds, if any (`None` for pure control flow with no
                operand, e.g. an unconditional jump).
            dest_reg: The destination register index, if this opcode
                writes one. Used to derive `name` (`"r{dest_reg}"`).
        """
        self.def_id = next(_next_def_id)  # independent of the object, unique

        self.opcode = entry
        self.value = value
        self.terminator = terminator
        self.statement = statement
        self.dest_reg = dest_reg

        # Shows: The expression generated by this instruction was inlined into another expression.
        self.definition_used = False
        # Shows: The register was subsequently read by an instruction.
        self.register_read = False

    # ------------------------------------------------------------------
    # Derived from `entry` - no longer separately stored/duplicated.
    # ------------------------------------------------------------------

    @property
    def address(self):
        return self.opcode.address

    @property
    def handler(self):
        return self.opcode.opcode

    @property
    def name(self):
        if self.dest_reg is None:
            return ""
        return f"r{self.dest_reg}"

    def __str__(self) -> str:
        return (
            f"OpcodeResult("
            f"address={self.address}, "
            f"handler={self.handler}, "
            f"name={self.name}, "
            f"value={self.value!r}, "
            f"used={self.definition_used})"
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "handler": self.handler,
            "address": self.address,
            "name": self.name,
            "value": self.value,
            "used": self.definition_used,
        }
