#!/usr/bin/env bash
# Fetch a hermesc binary for a specific Hermes bytecode version, pinned
# via tools/hermes/versions.json (the npm equivalent of vendor/hermes-dec's
# git_tags.sh).
#
# Unlike installing a full react-native/Expo sandbox app just to get at
# its bundled hermesc, this installs ONLY the `hermes-compiler` npm
# package directly - zero transitive dependencies, ~1s instead of
# 30-280s+.
#
# Usage:
#   ./tools/hermes/fetch_compiler.sh 96
#   ./tools/hermes/fetch_compiler.sh 98
#
# Installs into tools/hermes/compilers/<version>/node_modules/, which is
# exactly where hermes_disassembler.oracle already looks
# (compilers_root=tools/hermes/compilers).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSIONS_FILE="$SCRIPT_DIR/versions.json"
BYTECODE_VERSION="${1:?usage: $0 <bytecode-version>, e.g. $0 98}"

NPM_VERSION=$(python3 -c "
import json, sys
data = json.load(open('$VERSIONS_FILE'))
entry = data['versions'].get('$BYTECODE_VERSION')
if entry is None:
    sys.exit(f'bytecode version $BYTECODE_VERSION is not in {\"$VERSIONS_FILE\"}')
if entry['npm_version'] is None:
    sys.exit(f'bytecode version $BYTECODE_VERSION has no npm hermes-compiler release ({entry[\"notes\"]})')
print(entry['npm_version'])
")

TARGET_DIR="$SCRIPT_DIR/compilers/$BYTECODE_VERSION"
mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"

if [[ ! -f package.json ]]; then
    cat > package.json << EOF
{
  "private": true,
  "description": "Pinned hermesc for bytecode version $BYTECODE_VERSION. Generated by tools/hermes/fetch_compiler.sh - see tools/hermes/versions.json for the pin.",
  "dependencies": {
    "hermes-compiler": "$NPM_VERSION"
  }
}
EOF
fi

echo "📥 Installing hermes-compiler@$NPM_VERSION for bytecode version $BYTECODE_VERSION..."
npm install --no-audit --no-fund

# Sanity check: confirm the installed binary actually reports the
# bytecode version we asked for, rather than trusting the pin blindly.
BIN=$(find node_modules/hermes-compiler/hermesc -maxdepth 1 -type d ! -name hermesc | head -1)
case "$(uname -s)" in
    Linux*)  PLATFORM_BIN="linux64-bin" ;;
    Darwin*) PLATFORM_BIN="osx-bin" ;;
    *)       PLATFORM_BIN="win64-bin" ;;
esac
HERMESC_BIN="node_modules/hermes-compiler/hermesc/$PLATFORM_BIN/hermesc"
ACTUAL_VERSION=$("$HERMESC_BIN" -version 2>&1 | grep "HBC bytecode version" | grep -oE '[0-9]+')

if [[ "$ACTUAL_VERSION" != "$BYTECODE_VERSION" ]]; then
    echo "❌ Pin mismatch: installed hermes-compiler@$NPM_VERSION reports bytecode" \
         "version $ACTUAL_VERSION, expected $BYTECODE_VERSION. Update tools/hermes/versions.json." >&2
    exit 1
fi

echo "✅ $HERMESC_BIN confirmed at bytecode version $BYTECODE_VERSION"
