"""
Resolves a `builtin_id` operand (see `tools/hermes/generate_opcode_tables.py`'s
`_MANUAL_SEMANTICS` - `GetBuiltinClosure`/`CallBuiltin`/`CallBuiltinLong`'s
builtin-number operand) to its name, using the tables in
`hermes_disassembler/data/builtins/` (generated by
`tools/hermes/generate_builtins_table.py` from facebook/hermes's own
MIT-licensed `include/hermes/FrontEndDefs/Builtins.def`).

Confirmed against a real bundle: apps/testy/98's GetBuiltinClosure with
operand 57 resolves here to "spawnAsync" - matching real hermes-dec
output's own `# Built-in function: [#57 spawnAsync]` comment for the
exact same instruction (see
`tests/test_hermes_disassembler_builtins.py`).

Also confirmed - and corrected - by a full-bundle diff against real
hermes-dec's own output (`hbc-disassembler`, installed from
`vendor/hermes-dec` via `pip install -e .`, run directly against
apps/testy/96 and apps/testy/98): the 15 "private" builtins in each
table (`PRIVATE_BUILTIN(...)` entries in Builtins.def - e.g.
`copyDataProperties`, `arraySpread`, `apply`) were previously generated
with a `HermesBuiltin_` prefix that real hermes-dec's own name table
doesn't have - e.g. `# Built-in function: [#44
HermesBuiltin_copyDataProperties]` where real hermes-dec prints
`# Built-in function: [#44 copyDataProperties]`. This wasn't visible
from the earlier spot-check above (index 57's "spawnAsync" is a
`JS_BUILTIN` entry, a different macro, unaffected) or from the
generator script's own logic looking internally consistent - only a
literal, full-file diff against real hermes-dec output surfaced it.
Fixed in both the data files and
`tools/hermes/generate_builtins_table.py` (see that script's own
comment on its `PRIVATE_BUILTIN` pattern).
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from hermes_disassembler.core.Exceptions import HermesBytecodeError

__all__ = ["load_builtins_table", "resolve_builtin"]

_DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "builtins"


@lru_cache(maxsize=None)
def load_builtins_table(version: int) -> tuple[str, ...]:
    """
    Load the builtin-name table for `version`, in builtin-number order
    (index == builtin_id value), from
    `hermes_disassembler/data/builtins/<version>.json`.

    Raises `HermesBytecodeError` if no table has been generated for
    this version.
    """
    path = _DATA_DIR / f"{version}.json"
    if not path.is_file():
        raise HermesBytecodeError(
            f"no builtins table for bytecode version {version} "
            f"(looked for {path}) - generate one with "
            f"tools/hermes/generate_builtins_table.py and validate it "
            f"against a real bundle before trusting it (see module docstring)"
        )
    data = json.loads(path.read_text())
    return tuple(data["builtins"])


def resolve_builtin(version: int, index: int) -> str:
    """
    Resolve `builtin_id` value `index` to its name (e.g. "spawnAsync",
    "Math.abs", "copyDataProperties").

    Raises `IndexError` for an out-of-range index.
    """
    return load_builtins_table(version)[index]
