"""
Resolves a `builtin_id` operand (see `tools/hermes/generate_opcode_tables.py`'s
`_MANUAL_SEMANTICS` - `GetBuiltinClosure`/`CallBuiltin`/`CallBuiltinLong`'s
builtin-number operand) to its name, using the tables in
`hermes_disassembler/data/builtins/` (generated by
`tools/hermes/generate_builtins_table.py` from facebook/hermes's own
MIT-licensed `include/hermes/FrontEndDefs/Builtins.def`).

Confirmed against a real bundle: apps/testy/98's GetBuiltinClosure with
operand 57 resolves here to "spawnAsync" - matching real hermes-dec
output's own `# Built-in function: [#57 spawnAsync]` comment for the
exact same instruction (see
`tests/test_hermes_disassembler_builtins.py`).
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from hermes_disassembler.core.Exceptions import HermesBytecodeError

__all__ = ["load_builtins_table", "resolve_builtin"]

_DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "builtins"


@lru_cache(maxsize=None)
def load_builtins_table(version: int) -> tuple[str, ...]:
    """
    Load the builtin-name table for `version`, in builtin-number order
    (index == builtin_id value), from
    `hermes_disassembler/data/builtins/<version>.json`.

    Raises `HermesBytecodeError` if no table has been generated for
    this version.
    """
    path = _DATA_DIR / f"{version}.json"
    if not path.is_file():
        raise HermesBytecodeError(
            f"no builtins table for bytecode version {version} "
            f"(looked for {path}) - generate one with "
            f"tools/hermes/generate_builtins_table.py and validate it "
            f"against a real bundle before trusting it (see module docstring)"
        )
    data = json.loads(path.read_text())
    return tuple(data["builtins"])


def resolve_builtin(version: int, index: int) -> str:
    """
    Resolve `builtin_id` value `index` to its name (e.g. "spawnAsync",
    "Math.abs", "HermesBuiltin_copyDataProperties").

    Raises `IndexError` for an out-of-range index.
    """
    return load_builtins_table(version)[index]
