"""
Decodes individual Hermes bytecode instructions: opcode byte -> name +
typed operands, using the tables in `hermes_disassembler/data/opcodes/`
(generated by `tools/hermes/generate_opcode_tables.py` from facebook/hermes's
own MIT-licensed `BytecodeList.def`, at the exact git commit each pinned
`hermes-compiler` npm package was built from).

Operand type sizes: hermes/include/hermes/BCGen/HBC/BytecodeList.def's
own `DEFINE_OPERAND_TYPE` declarations (Reg8=uint8_t, Reg32=uint32_t,
UInt8/16/32, Addr8=int8_t, Addr32=int32_t, Imm32=int32_t, Double=double)
- Addr8/Addr32 are SIGNED (jump targets are offsets relative to the
current instruction, and can go backward).

Cross-version gotcha (see `tools/hermes/generate_opcode_tables.py`'s
own docstring for the full story): a bytecode version's opcode table
must come from the EXACT commit its pinned `hermes-compiler` npm
package was built from - not a same-numbered git tag, not a
neighboring version's table. The v96 table here was regenerated after
a first attempt (from the `v0.12.0` tag) turned out to differ from the
real pinned commit by two inserted opcodes, silently shifting every
subsequent opcode number by 2 and corrupting every instruction after
byte 2 of the first affected function. That regression was only caught
by decoding a real, complete function's bytecode and diffing every
single instruction against `tools/hermes/dump_bytecode.sh`'s oracle
output - not by unit-testing the parser against the .def file in
isolation, which happily "worked" on the wrong commit too. See
`tests/test_hermes_disassembler_opcode.py` for that full-function diff,
kept as a regression test for exactly this failure mode.

Bytecode 99 is NOT supported here: its opcode set is confirmed to
differ from 98's (NewTypedObjectWithBuffer added, CacheNewObject
removed, ToUint32 added - diffed directly against 98's table at their
respective pinned commits) and there is no apps/testy/99 bundle to
validate a generated table against, so one hasn't been generated.
"""
from __future__ import annotations

import json
import struct
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from hermes_disassembler.core.Exceptions import HermesBytecodeError, TruncatedFileError

__all__ = ["Instruction", "OperandType", "load_opcode_table", "decode_instruction", "decode_function"]

_DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "opcodes"

#: (struct format char, byte size) per BytecodeList.def's DEFINE_OPERAND_TYPE.
#: Addr8/Addr32 are signed - jump offsets can be negative (backward jumps).
OperandType = str  # e.g. "Reg8", "UInt16", "Addr32" - kept as plain str, not an enum, since new operand types are only ever added, never renamed, by upstream
_OPERAND_STRUCT = {
    "Reg8": ("B", 1), "Reg32": ("I", 4),
    "UInt8": ("B", 1), "UInt16": ("H", 2), "UInt32": ("I", 4),
    "Addr8": ("b", 1), "Addr32": ("i", 4),
    "Imm32": ("i", 4),
    "Double": ("d", 8),
}


@dataclass(frozen=True, slots=True)
class Instruction:
    """One decoded instruction: its opcode name, raw operand values (in
    the order BytecodeList.def declares them), and total byte size
    (opcode byte + all operands) - `offset + size` is the next
    instruction's offset."""

    offset: int  # absolute byte offset in the file
    opcode: int  # raw opcode byte value
    name: str
    operands: tuple[int | float, ...]
    size: int


@lru_cache(maxsize=None)
def load_opcode_table(version: int) -> tuple[tuple[str, tuple[str, ...], dict[int, str]], ...]:
    """
    Load the (name, operand_types, semantics) table for `version`, in
    opcode-number order (index == opcode byte value), from
    `hermes_disassembler/data/opcodes/<version>.json`.

    `semantics` maps a 0-based operand index to `"string_id"` /
    `"function_id"` / `"bigint_id"` for operands BytecodeList.def tags
    with `OPERAND_STRING_ID`/`_FUNCTION_ID`/`_BIGINT_ID` - e.g.
    `GetByIdShort`'s 4th operand is a plain `UInt8` by raw encoding but
    semantically a string-table index (`{3: "string_id"}`). Empty dict
    for opcodes with no such operand (most of them).

    Raises `HermesBytecodeError` if no table has been generated for
    this version (see module docstring re: bytecode 99).
    """
    path = _DATA_DIR / f"{version}.json"
    if not path.is_file():
        raise HermesBytecodeError(
            f"no opcode table for bytecode version {version} "
            f"(looked for {path}) - generate one with "
            f"tools/hermes/generate_opcode_tables.py and validate it "
            f"against a real bundle before trusting it (see module docstring)"
        )
    data = json.loads(path.read_text())
    return tuple(
        (
            entry["name"],
            tuple(entry["operands"]),
            {int(i): tag for i, tag in entry.get("semantics", {}).items()},
        )
        for entry in data["opcodes"]
    )


def decode_instruction(data: bytes, offset: int, version: int) -> Instruction:
    """
    Decode one instruction at `offset` in `data`.

    Raises `TruncatedFileError` if the opcode or any operand would read
    past the end of `data`, and `HermesBytecodeError` for a raw opcode
    byte with no entry in this version's table (a corrupt file or a
    genuinely unknown/reserved opcode - never silently skipped).
    """
    table = load_opcode_table(version)
    if offset >= len(data):
        raise TruncatedFileError("instruction opcode byte", offset + 1, len(data))

    opcode = data[offset]
    if opcode >= len(table):
        raise HermesBytecodeError(
            f"opcode byte {opcode} at file offset {offset} has no entry in "
            f"the bytecode {version} table (only {len(table)} opcodes known) - "
            f"corrupt data, or this table needs regenerating"
        )
    name, operand_types, _semantics = table[opcode]

    pos = offset + 1
    operands: list[int | float] = []
    for operand_type in operand_types:
        fmt, size = _OPERAND_STRUCT[operand_type]
        if pos + size > len(data):
            raise TruncatedFileError(f"{name} operand ({operand_type})", pos + size, len(data))
        (value,) = struct.unpack_from(f"<{fmt}", data, pos)
        operands.append(value)
        pos += size

    return Instruction(offset=offset, opcode=opcode, name=name, operands=tuple(operands), size=pos - offset)


def decode_function(data: bytes, offset: int, bytecode_size: int, version: int) -> tuple[Instruction, ...]:
    """
    Decode every instruction in `[offset, offset + bytecode_size)`.

    `offset`/`bytecode_size` (from `FunctionHeaderEntry`) point directly
    at the instruction stream with no preamble to skip - this was
    initially suspected NOT to hold for functions with
    `has_exception_handler=True` (an early investigation misread a
    stale-opcode-table bug as a missing exception-handler-table prefix),
    but decoding every function in both apps/testy/96 and
    apps/testy/98 - has_exception_handler=True functions included
    (2.6% and 3.3% of each bundle respectively) - lands exactly on
    `offset + bytecode_size` with zero errors; see
    `tests/test_hermes_disassembler_opcode.py`'s
    `test_every_function_in_bundle_decodes_cleanly`. Wherever Hermes
    stores the exception handler table itself, it isn't inline before
    the bytecode.

    Raises `HermesBytecodeError` if decoding doesn't land exactly on
    `offset + bytecode_size` after the last instruction (a strong
    signal something upstream - the offset, the size, or the opcode
    table - is wrong, the same way a two-opcode table drift was caught
    during development; see module docstring).
    """
    end = offset + bytecode_size
    instructions = []
    pos = offset
    while pos < end:
        instruction = decode_instruction(data, pos, version)
        instructions.append(instruction)
        pos += instruction.size

    if pos != end:
        raise HermesBytecodeError(
            f"decoding [{offset}:{end}) overran by {pos - end} bytes - "
            f"opcode table or function bounds are likely wrong for this input"
        )

    return tuple(instructions)
